% Preprocessing
gui_fn = 'brant_Preprocessing';
gui_func = @brant_preprocess_jobman;
gui_version = '3.37';

clear gui_parameters

gui_parameters{1}.subj.text.inputfile = '';
gui_parameters{1}.subj.text.dirs = '';
gui_parameters{1}.subj.spm.dirs = '';
gui_parameters{1}.subj.filetype = 'fmri.nii';
gui_parameters{1}.subj.is4d = 1;
gui_parameters{1}.subj.out.selected = 0;
gui_parameters{1}.subj.out.dir = [pwd filesep 'OUTPUTS'];
gui_parameters{1}.subj.out.nmpos = 1;

gui_parameters{1}.pref = struct( ...
    'parallel','off', ...
    'parallel_workers',2, ...
    'sync',1, ...
    'order',{'slicetiming' 'realign' 'coregister' 'normalise12' 'denoise' 'smooth'}, ...
    'dirs_in_text',0, ...
    'norm12_ind',1 ...
    );

gui_parameters{1}.ind = struct( ...
    'slicetiming',1, ...
    'realign',1, ...
    'coregister',1, ...
    'normalise',0, ...
    'normalise12',1, ...
    'denoise',1, ...
    'smooth',0 ...
    );

gui_parameters{1}.slicetiming = struct( ...
    'slice_order',0, ...
    'tr',0, ...
    'refslice',0, ...
    'prefix','a' ...
    );

gui_parameters{1}.realign.eoptions = struct( ...
    'quality',0.9000, ...
    'sep',4, ...
    'fwhm',5, ...
    'rtm',1, ...
    'wrap',[0 0 0], ...
    'interp',4 ...
    );
gui_parameters{1}.realign.roptions = struct( ...
    'which',[2 1], ...
    'interp',4, ...
    'wrap',[0 0 0], ...
    'mask',1, ...
    'prefix','r' ...
    );

gui_parameters{1}.coregister.subj = struct( ...
    'filetype_ref','mean*.nii', ...
    'filetype_src','co*.nii', ...
    'seg_bet_ind',1 ...
    );
gui_parameters{1}.coregister.eoptions = struct( ...
    'cost_fun','nmi', ...
    'sep',[4 2], ...
    'tol',[0.0200 0.0200 0.0200 1.0000e-03 1.0000e-03 1.0000e-03 0.0100 0.0100 0.0100 1.0000e-03 1.0000e-03 1.0000e-03], ...
    'fwhm',[7 7] ...
    );

%      normalise: [1×1 struct]
%    normalise12: [1×1 struct]
%        denoise: [1×1 struct]
%         smooth: [1×1 struct]



